# Generated by Django 4.0.6 on 2022-07-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_numb', models.DecimalField(decimal_places=1, max_digits=5)),
                ('order_numb', models.DecimalField(decimal_places=1, max_digits=10)),
                ('price_usd', models.DecimalField(decimal_places=1, max_digits=10)),
                ('price_rub', models.DecimalField(decimal_places=1, max_digits=10)),
                ('delivery_date', models.DateField()),
            ],
        ),
    ]
